module Interactor
  class Context
    def initialize: (Hash[Symbol, untyped]) -> void
    def success?: () -> bool
    def failure?: () -> bool
    def fail!: (Hash[Symbol, untyped]) -> void
  end

  module Organizer
    def organize: (untyped) -> void
    def call: () -> Context
  end

  def context: () -> untyped
end
